#Requires AutoHotkey v2.0+
#UseHook

; Suppress the default action of modifier keys when pressed alone
LAlt::Return
RAlt::Return
CapsLock::Return
SetCapslockState "AlwaysOff"

; Layer de Números (LAlt)
LAlt & n::SendInput "{1}"
LAlt & m::SendInput "{2}"
LAlt & ,::SendInput "{3}"
LAlt & j::SendInput "{4}"
LAlt & k::SendInput "{5}"
LAlt & l::SendInput "{6}"
LAlt & u::SendInput "{7}"
LAlt & i::SendInput "{8}"
LAlt & o::SendInput "{9}"
LAlt & p::SendInput "{0}"
LAlt & y::SendInput "{/}"
LAlt & h::SendInput "{*}"
LAlt & .::SendInput "{-}"
LAlt & `;::SendInput "{+}"

; Symbol Layer (CapsLock)
CapsLock & n::SendInput "{{}"
CapsLock & m::SendInput "{}}"
CapsLock & j::SendInput "{(}"
CapsLock & k::SendInput "{)}"
CapsLock & u::SendInput "{[}"
CapsLock & i::SendInput "{]}"
CapsLock & l::SendInput "{=}"
CapsLock & h::SendInput "{_}"
CapsLock & o::SendInput "{&}"   
CapsLock & p::SendInput "{@}"
CapsLock & y::SendInput "{#}"
CapsLock & .::SendInput "{$}"
CapsLock & ,::SendInput "{%}"
CapsLock & `;::SendInput "{!}"
CapsLock & [::~
CapsLock & ]::^

; Function Layer (RAlt ou Control+Shift)
RAlt & q::SendInput "{F1}"
RAlt & w::SendInput "{F2}"
RAlt & e::SendInput "{F3}"
RAlt & r::SendInput "{F4}"
RAlt & a::SendInput "{F5}"
RAlt & s::SendInput "{F6}"
RAlt & d::SendInput "{F7}"
RAlt & f::SendInput "{F8}"
RAlt & z::SendInput "{F9}"
RAlt & x::SendInput "{F10}"
RAlt & c::SendInput "{F11}"
RAlt & v::SendInput "{F12}"
RAlt & h::SendInput "{Left}"
RAlt & j::SendInput "{Down}"
RAlt & k::SendInput "{Up}"
RAlt & l::SendInput "{Right}"
RAlt & n::SendInput "+{Left}"
RAlt & m::SendInput "+{Down}"
RAlt & ,::SendInput "+{Up}"
RAlt & .::SendInput "+{Right}"
RAlt & y::SendInput "{Home}"
RAlt & u::SendInput "{PgDn}"
RAlt & i::SendInput "{PgUp}"
RAlt & o::SendInput "{End}"
RAlt & Space::SendInput "{Esc}"
^+q::SendInput "{F1}"
^+w::SendInput "{F2}"
^+e::SendInput "{F3}"
^+r::SendInput "{F4}"
^+a::SendInput "{F5}"
^+s::SendInput "{F6}"
^+d::SendInput "{F7}"
^+f::SendInput "{F8}"
^+z::SendInput "{F9}"
^+x::SendInput "{F10}"
^+c::SendInput "{F11}"
^+v::SendInput "{F12}"
^+h::SendInput "{Left}"
^+j::SendInput "{Down}"
^+k::SendInput "{Up}"
^+l::SendInput "{Right}"
^+n::SendInput "+{Left}"
^+m::SendInput "+{Down}"
^+,::SendInput "+{Up}"
^+.::SendInput "+{Right}"
^+y::SendInput "{Home}"
^+u::SendInput "{PgDn}"
^+i::SendInput "{PgUp}"
^+o::SendInput "{End}"
^+Space::SendInput "{Esc}"